name: Arduino CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1

    - name: Install Inkplate board platform
      run: |
        arduino-cli config init
        arduino-cli config add board_manager.additional_urls https://github.com/SolderedElectronics/Dasduino-Board-Definitions-for-Arduino-IDE/raw/master/package_Dasduino_Boards_index.json
        arduino-cli core update-index
        arduino-cli core install Inkplate_Boards:esp32

    - name: Install required libraries
      run: |
        arduino-cli lib install InkplateLibrary
        arduino-cli lib install WiFiManager
        arduino-cli lib install ArduinoJson

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn Inkplate_Boards:esp32:Inkplate2 pregometer.ino
